name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1) Quellcode ziehen
      - uses: actions/checkout@v4

      # 2) PHP einrichten (gepinnt auf deinen Commit – kann bleiben)
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      # 3) Node + npm einrichten und cachen
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'        # ggf. an dein Projekt anpassen
          cache: 'npm'              # beschleunigt Folge‑Runs

      # 4) .env kopieren
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # 5) Backend‑Dependencies
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # 6) Frontend‑Dependencies
      - name: Install NPM dependencies
        run: npm ci

      # 7) Vite‑Build erzeugen (liefert manifest.json)
      - name: Build frontend assets
        env:
          CI: true                 # erzwingt non‑interaktives Build
        run: npm run build

      # 8) App‑Key, Rechte & DB
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 9) PHPUnit / Pest ausführen
      - name: Execute tests (Unit and Feature tests)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          APP_ENV: testing
        run: php artisan test
